=== owenvoke/keep-data/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Keep Schema",
    "description": "A list of castles or fortifications.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "description": "The unique identifier (UUID v7) of the castle or fortification.",
                "type": "string",
                "format": "uuid"
            },
            "name": {
                "description": "The name of the castle or fortification.",
                "type": "string"
            },
            "country": {
                "description": "The country of the castle or fortification.",
                "$ref": "#/definitions/country"
            },
            "region": {
                "description": "The region of the castle or fortification (this is only relevant for UK castles).",
                "$ref": "#/definitions/region"
            },
            "coordinates": {
                "description": "The coordinates of the castle or fortification.",
                "$ref": "#/definitions/coordinates"
            },
            "accessible": {
                "description": "Whether the castle or fortification is accessible to the public.",
                "type": "boolean"
            },
            "alternativeNames": {
                "description": "The alternative names of the castle or fortification.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "built": {
                "description": "The century or date that the castle or fortification was built.",
                "type": "string",
                "pattern": "^(?:\\d{1,4}|\\d{1,4} BCE|(?:\\d{1,2}|\\d{1,2}-\\d{1,2})(?:st|nd|rd|th) Century|(?:\\d{1,2}|\\d{1,2}-\\d{1,2})(?:st|nd|rd|th) Century BCE)$"
            },
            "condition": {
                "description": "The condition of the castle or fortification.",
                "$ref": "#/definitions/condition"
            },
            "description": {
                "description": "The description of the castle or fortification.",
                "type": "string"
            },
            "homepage": {
                "$comment": "Use an English version if available.",
                "description": "The homepage of the castle or fortification.",
                "type": "string",
                "format": "uri-reference"
            },
            "ownedBy": {
                "description": "The owner of the castle or fortification.",
                "type": "string"
            },
            "type": {
                "description": "The type of the castle or fortification.",
                "$ref": "#/definitions/type"
            }
        },
        "required": [
            "id",
            "name",
            "country",
            "coordinates",
            "built",
            "condition",
            "ownedBy",
            "type"
        ],
        "additionalProperties": false
    },
    "definitions": {
        "coordinates": {
            "description": "A set of coordinates in the form of latitude and longitude.",
            "type": "object",
            "properties": {
                "latitude": {
                    "description": "The latitude of the coordinates to a maximum of 5 decimal places (within 1.11m accuracy).",
                    "type": "number"
                },
                "longitude": {
                    "description": "The longitude of the coordinates to a maximum of 5 decimal places (within 1.11m accuracy).",
                    "type": "number"
                }
            },
            "required": [
                "latitude",
                "longitude"
            ],
            "examples": [
                {
                    "latitude": 51.48389,
                    "longitude": -0.60440
                }
            ]
        },
        "type": {
            "description": "The type of a castle or fortification.",
            "enum": [
                "Artillery Fort",
                "Concentric",
                "Folly",
                "Fort",
                "Fortified Manor House",
                "Keepless",
                "Motte and Bailey",
                "Palace",
                "Round Keep",
                "Shell Keep",
                "Square Keep",
                "Tower House",
                "Unknown"
            ]
        },
        "condition": {
            "description": "The condition of a castle or fortification.",
            "enum": [
                "Earthworks",
                "Fragmented Remains",
                "Intact",
                "No Visible Remains",
                "Partial Ruins",
                "Partially Restored",
                "Rebuilt",
                "Restored",
                "Ruins"
            ]
        },
        "country": {
            "$comment": "See https://www.iso.org/iso-3166-country-codes.html for more information.",
            "description": "An ISO 3166 identifier for a country.",
            "enum": [
                "AD",
                "AE",
                "AF",
                "AG",
                "AI",
                "AL",
                "AM",
                "AO",
                "AQ",
                "AR",
                "AS",
                "AT",
                "AU",
                "AW",
                "AX",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BL",
                "BM",
                "BN",
                "BO",
                "BQ",
                "BR",
                "BS",
                "BT",
                "BV",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CC",
                "CD",
                "CF",
                "CG",
                "CH",
                "CI",
                "CK",
                "CL",
                "CM",
                "CN",
                "CO",
                "CR",
                "CU",
                "CV",
                "CW",
                "CX",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "EH",
                "ER",
                "ES",
                "ET",
                "FI",
                "FJ",
                "FK",
                "FM",
                "FO",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GF",
                "GG",
                "GH",
                "GI",
                "GL",
                "GM",
                "GN",
                "GP",
                "GQ",
                "GR",
                "GS",
                "GT",
                "GU",
                "GW",
                "GY",
                "HK",
                "HM",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IM",
                "IN",
                "IO",
                "IQ",
                "IR",
                "IS",
                "IT",
                "JE",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KP",
                "KR",
                "KW",
                "KY",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "LY",
                "MA",
                "MC",
                "MD",
                "ME",
                "MF",
                "MG",
                "MH",
                "MK",
                "ML",
                "MM",
                "MN",
                "MO",
                "MP",
                "MQ",
                "MR",
                "MS",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NC",
                "NE",
                "NF",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NU",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PF",
                "PG",
                "PH",
                "PK",
                "PL",
                "PM",
                "PN",
                "PR",
                "PS",
                "PT",
                "PW",
                "PY",
                "QA",
                "RE",
                "RO",
                "RS",
                "RU",
                "RW",
                "SA",
                "SB",
                "SC",
                "SD",
                "SE",
                "SG",
                "SH",
                "SI",
                "SJ",
                "SK",
                "SL",
                "SM",
                "SN",
                "SO",
                "SR",
                "SS",
                "ST",
                "SV",
                "SX",
                "SY",
                "SZ",
                "TC",
                "TD",
                "TF",
                "TG",
                "TH",
                "TJ",
                "TK",
                "TL",
                "TM",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TZ",
                "UA",
                "UG",
                "UM",
                "US",
                "UY",
                "UZ",
                "VA",
                "VC",
                "VE",
                "VG",
                "VI",
                "VN",
                "VU",
                "WF",
                "WS",
                "YE",
                "YT",
                "ZA",
                "ZM",
                "ZW"
            ]
        },
        "region": {
            "$comment": "See https://wikipedia.org/wiki/ISO_3166-2:GB#Other_codes for more information.",
            "description": "A BS 6879 identifier for a region.",
            "enum": [
                "GB-ENG",
                "GB-NIR",
                "GB-SCT",
                "GB-WLS"
            ]
        }
    }
}

=== owenvoke/keep-data/data/es.json
[
    {
        "id": "019dde34-11b4-776b-91cf-508ad45d43bd",
        "name": "Palace of the Kings of Navarre of Olite",
        "country": "ES",
        "coordinates": {
            "latitude": 42.48167,
            "longitude": -1.64944
        },
        "alternativeNames": [
            "Royal Palace of Olite"
        ],
        "built": "13th Century",
        "condition": "Restored",
        "homepage": "https://palaciorealolite.com/en",
        "ownedBy": "Government of Navarre",
        "type": "Palace"
    }
]

=== owenvoke/keep-data/data/no.json
[
    {
        "id": "019da4ea-7445-717d-981d-0f3f93c3e34f",
        "name": "Torgauten Fort",
        "country": "NO",
        "coordinates": {
            "latitude": 59.171895069044474,
            "longitude": 10.842087693955028
        },
        "built": "20th Century",
        "condition": "Fragmented Remains",
        "homepage": "https://www.visitoestfold.com/listing/turperler%3A-torgauten-fort/584921306",
        "ownedBy": "Den norske stat",
        "type": "Artillery Fort"
    }
]

=== owenvoke/keep-data/data/je.json
[
    {
        "id": "019daf22-5780-71d3-aef7-d30ab83ab9d3",
        "name": "Elizabeth Castle",
        "country": "JE",
        "coordinates": {
            "latitude": 49.175,
            "longitude": -2.125
        },
        "built": "16th Century",
        "condition": "Intact",
        "homepage": "https://www.jerseyheritage.org/visit/places-to-visit/elizabeth-castle",
        "ownedBy": "Jersey Heritage Trust",
        "type": "Artillery Fort"
    },
    {
        "id": "019daf22-5780-71d3-aef7-d49cab399b3f",
        "name": "Grosnez Castle",
        "country": "JE",
        "coordinates": {
            "latitude": 49.25747,
            "longitude": -2.24651
        },
        "built": "14th Century",
        "condition": "Ruins",
        "ownedBy": "Rosel Estates Limited / Jersey Heritage Trust",
        "type": "Square Keep"
    },
    {
        "id": "019daf22-5780-71d3-aef7-d83c394ad8ae",
        "name": "Mont Orgueil",
        "country": "JE",
        "coordinates": {
            "latitude": 49.1994,
            "longitude": -2.0194
        },
        "alternativeNames": [
            "Gorey Castle",
            "Old Castle",
            "Lé Vièr Châté"
        ],
        "built": "13-15th Century",
        "condition": "Intact",
        "ownedBy": "Jersey Heritage Trust",
        "type": "Concentric"
    }
]
